// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: pluginsocket.proto

package kong_plugin_protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ServiceKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ServiceKey) Reset() {
	*x = ServiceKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceKey) ProtoMessage() {}

func (x *ServiceKey) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceKey.ProtoReflect.Descriptor instead.
func (*ServiceKey) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CertificateKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CertificateKey) Reset() {
	*x = CertificateKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CertificateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateKey) ProtoMessage() {}

func (x *CertificateKey) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateKey.ProtoReflect.Descriptor instead.
func (*CertificateKey) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                      string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt               int64       `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt               int64       `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name                    string      `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Protocols               []string    `protobuf:"bytes,5,rep,name=protocols,proto3" json:"protocols,omitempty"`
	Methods                 []string    `protobuf:"bytes,6,rep,name=methods,proto3" json:"methods,omitempty"`
	Hosts                   []string    `protobuf:"bytes,7,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Paths                   []string    `protobuf:"bytes,8,rep,name=paths,proto3" json:"paths,omitempty"`
	Headers                 []string    `protobuf:"bytes,9,rep,name=headers,proto3" json:"headers,omitempty"`
	HttpsRedirectStatusCode int32       `protobuf:"varint,10,opt,name=https_redirect_status_code,json=httpsRedirectStatusCode,proto3" json:"https_redirect_status_code,omitempty"`
	RegexPriority           int32       `protobuf:"varint,11,opt,name=regex_priority,json=regexPriority,proto3" json:"regex_priority,omitempty"`
	StripPath               bool        `protobuf:"varint,12,opt,name=strip_path,json=stripPath,proto3" json:"strip_path,omitempty"`
	PreserveHost            bool        `protobuf:"varint,13,opt,name=preserve_host,json=preserveHost,proto3" json:"preserve_host,omitempty"`
	Snis                    []string    `protobuf:"bytes,14,rep,name=snis,proto3" json:"snis,omitempty"`
	Sources                 []string    `protobuf:"bytes,15,rep,name=sources,proto3" json:"sources,omitempty"`
	Destinations            []string    `protobuf:"bytes,16,rep,name=destinations,proto3" json:"destinations,omitempty"`
	Tags                    []string    `protobuf:"bytes,17,rep,name=tags,proto3" json:"tags,omitempty"`
	Service                 *ServiceKey `protobuf:"bytes,18,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{2}
}

func (x *Route) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Route) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Route) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Route) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *Route) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *Route) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *Route) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *Route) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Route) GetHttpsRedirectStatusCode() int32 {
	if x != nil {
		return x.HttpsRedirectStatusCode
	}
	return 0
}

func (x *Route) GetRegexPriority() int32 {
	if x != nil {
		return x.RegexPriority
	}
	return 0
}

func (x *Route) GetStripPath() bool {
	if x != nil {
		return x.StripPath
	}
	return false
}

func (x *Route) GetPreserveHost() bool {
	if x != nil {
		return x.PreserveHost
	}
	return false
}

func (x *Route) GetSnis() []string {
	if x != nil {
		return x.Snis
	}
	return nil
}

func (x *Route) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *Route) GetDestinations() []string {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *Route) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Route) GetService() *ServiceKey {
	if x != nil {
		return x.Service
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt         int64           `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         int64           `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name              string          `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Retries           int32           `protobuf:"varint,5,opt,name=retries,proto3" json:"retries,omitempty"`
	Protocol          string          `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Host              string          `protobuf:"bytes,7,opt,name=host,proto3" json:"host,omitempty"`
	Port              int32           `protobuf:"varint,8,opt,name=port,proto3" json:"port,omitempty"`
	Path              string          `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`
	ConnectTimeout    int32           `protobuf:"varint,10,opt,name=connect_timeout,json=connectTimeout,proto3" json:"connect_timeout,omitempty"`
	WriteTimeout      int32           `protobuf:"varint,11,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	ReadTimeout       int32           `protobuf:"varint,12,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	Tags              []string        `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	ClientCertificate *CertificateKey `protobuf:"bytes,14,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{3}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Service) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *Service) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Service) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Service) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Service) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Service) GetConnectTimeout() int32 {
	if x != nil {
		return x.ConnectTimeout
	}
	return 0
}

func (x *Service) GetWriteTimeout() int32 {
	if x != nil {
		return x.WriteTimeout
	}
	return 0
}

func (x *Service) GetReadTimeout() int32 {
	if x != nil {
		return x.ReadTimeout
	}
	return 0
}

func (x *Service) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Service) GetClientCertificate() *CertificateKey {
	if x != nil {
		return x.ClientCertificate
	}
	return nil
}

type Consumer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt int64    `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Username  string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	CustomId  string   `protobuf:"bytes,4,opt,name=custom_id,json=customId,proto3" json:"custom_id,omitempty"`
	Tags      []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *Consumer) Reset() {
	*x = Consumer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Consumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consumer) ProtoMessage() {}

func (x *Consumer) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consumer.ProtoReflect.Descriptor instead.
func (*Consumer) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{4}
}

func (x *Consumer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Consumer) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Consumer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Consumer) GetCustomId() string {
	if x != nil {
		return x.CustomId
	}
	return ""
}

func (x *Consumer) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AuthenticatedCredential struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConsumerId string `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
}

func (x *AuthenticatedCredential) Reset() {
	*x = AuthenticatedCredential{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticatedCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatedCredential) ProtoMessage() {}

func (x *AuthenticatedCredential) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatedCredential.ProtoReflect.Descriptor instead.
func (*AuthenticatedCredential) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{5}
}

func (x *AuthenticatedCredential) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthenticatedCredential) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type MemoryStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LuaSharedDicts *MemoryStats_LuaSharedDicts `protobuf:"bytes,1,opt,name=lua_shared_dicts,json=luaSharedDicts,proto3" json:"lua_shared_dicts,omitempty"`
	WorkersLuaVms  []*MemoryStats_WorkerLuaVm  `protobuf:"bytes,2,rep,name=workers_lua_vms,json=workersLuaVms,proto3" json:"workers_lua_vms,omitempty"`
}

func (x *MemoryStats) Reset() {
	*x = MemoryStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStats) ProtoMessage() {}

func (x *MemoryStats) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStats.ProtoReflect.Descriptor instead.
func (*MemoryStats) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{6}
}

func (x *MemoryStats) GetLuaSharedDicts() *MemoryStats_LuaSharedDicts {
	if x != nil {
		return x.LuaSharedDicts
	}
	return nil
}

func (x *MemoryStats) GetWorkersLuaVms() []*MemoryStats_WorkerLuaVm {
	if x != nil {
		return x.WorkersLuaVms
	}
	return nil
}

type CmdGetPluginNames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CmdGetPluginNames) Reset() {
	*x = CmdGetPluginNames{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetPluginNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetPluginNames) ProtoMessage() {}

func (x *CmdGetPluginNames) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetPluginNames.ProtoReflect.Descriptor instead.
func (*CmdGetPluginNames) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{7}
}

type CmdGetPluginInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CmdGetPluginInfo) Reset() {
	*x = CmdGetPluginInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetPluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetPluginInfo) ProtoMessage() {}

func (x *CmdGetPluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetPluginInfo.ProtoReflect.Descriptor instead.
func (*CmdGetPluginInfo) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{8}
}

func (x *CmdGetPluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CmdStartInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config string `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *CmdStartInstance) Reset() {
	*x = CmdStartInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdStartInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdStartInstance) ProtoMessage() {}

func (x *CmdStartInstance) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdStartInstance.ProtoReflect.Descriptor instead.
func (*CmdStartInstance) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{9}
}

func (x *CmdStartInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CmdStartInstance) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type CmdGetInstanceStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId int32 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
}

func (x *CmdGetInstanceStatus) Reset() {
	*x = CmdGetInstanceStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdGetInstanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetInstanceStatus) ProtoMessage() {}

func (x *CmdGetInstanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetInstanceStatus.ProtoReflect.Descriptor instead.
func (*CmdGetInstanceStatus) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{10}
}

func (x *CmdGetInstanceStatus) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type CmdCloseInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId int32 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
}

func (x *CmdCloseInstance) Reset() {
	*x = CmdCloseInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdCloseInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdCloseInstance) ProtoMessage() {}

func (x *CmdCloseInstance) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdCloseInstance.ProtoReflect.Descriptor instead.
func (*CmdCloseInstance) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{11}
}

func (x *CmdCloseInstance) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type CmdHandleEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceId int32  `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	EventName  string `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
}

func (x *CmdHandleEvent) Reset() {
	*x = CmdHandleEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdHandleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdHandleEvent) ProtoMessage() {}

func (x *CmdHandleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdHandleEvent.ProtoReflect.Descriptor instead.
func (*CmdHandleEvent) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{12}
}

func (x *CmdHandleEvent) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *CmdHandleEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

type Map struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	M map[string]string `protobuf:"bytes,1,rep,name=m,proto3" json:"m,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Map) Reset() {
	*x = Map{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map) ProtoMessage() {}

func (x *Map) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map.ProtoReflect.Descriptor instead.
func (*Map) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{13}
}

func (x *Map) GetM() map[string]string {
	if x != nil {
		return x.M
	}
	return nil
}

type StepData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId int64 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Types that are assignable to Data:
	//	*StepData_B
	//	*StepData_I
	//	*StepData_F
	//	*StepData_S
	//	*StepData_M
	//	*StepData_Error
	//	*StepData_Credential
	//	*StepData_Route
	//	*StepData_Service
	//	*StepData_Consumer
	//	*StepData_MemoryStats
	Data isStepData_Data `protobuf_oneof:"data"`
}

func (x *StepData) Reset() {
	*x = StepData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StepData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepData) ProtoMessage() {}

func (x *StepData) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepData.ProtoReflect.Descriptor instead.
func (*StepData) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{14}
}

func (x *StepData) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (m *StepData) GetData() isStepData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *StepData) GetB() bool {
	if x, ok := x.GetData().(*StepData_B); ok {
		return x.B
	}
	return false
}

func (x *StepData) GetI() int64 {
	if x, ok := x.GetData().(*StepData_I); ok {
		return x.I
	}
	return 0
}

func (x *StepData) GetF() float64 {
	if x, ok := x.GetData().(*StepData_F); ok {
		return x.F
	}
	return 0
}

func (x *StepData) GetS() string {
	if x, ok := x.GetData().(*StepData_S); ok {
		return x.S
	}
	return ""
}

func (x *StepData) GetM() *Map {
	if x, ok := x.GetData().(*StepData_M); ok {
		return x.M
	}
	return nil
}

func (x *StepData) GetError() string {
	if x, ok := x.GetData().(*StepData_Error); ok {
		return x.Error
	}
	return ""
}

func (x *StepData) GetCredential() *AuthenticatedCredential {
	if x, ok := x.GetData().(*StepData_Credential); ok {
		return x.Credential
	}
	return nil
}

func (x *StepData) GetRoute() *Route {
	if x, ok := x.GetData().(*StepData_Route); ok {
		return x.Route
	}
	return nil
}

func (x *StepData) GetService() *Service {
	if x, ok := x.GetData().(*StepData_Service); ok {
		return x.Service
	}
	return nil
}

func (x *StepData) GetConsumer() *Consumer {
	if x, ok := x.GetData().(*StepData_Consumer); ok {
		return x.Consumer
	}
	return nil
}

func (x *StepData) GetMemoryStats() *MemoryStats {
	if x, ok := x.GetData().(*StepData_MemoryStats); ok {
		return x.MemoryStats
	}
	return nil
}

type isStepData_Data interface {
	isStepData_Data()
}

type StepData_B struct {
	B bool `protobuf:"varint,31,opt,name=b,proto3,oneof"`
}

type StepData_I struct {
	I int64 `protobuf:"varint,32,opt,name=i,proto3,oneof"`
}

type StepData_F struct {
	F float64 `protobuf:"fixed64,33,opt,name=f,proto3,oneof"`
}

type StepData_S struct {
	S string `protobuf:"bytes,34,opt,name=s,proto3,oneof"`
}

type StepData_M struct {
	M *Map `protobuf:"bytes,35,opt,name=m,proto3,oneof"`
}

type StepData_Error struct {
	Error string `protobuf:"bytes,36,opt,name=error,proto3,oneof"`
}

type StepData_Credential struct {
	Credential *AuthenticatedCredential `protobuf:"bytes,40,opt,name=credential,proto3,oneof"`
}

type StepData_Route struct {
	Route *Route `protobuf:"bytes,41,opt,name=route,proto3,oneof"`
}

type StepData_Service struct {
	Service *Service `protobuf:"bytes,42,opt,name=service,proto3,oneof"`
}

type StepData_Consumer struct {
	Consumer *Consumer `protobuf:"bytes,43,opt,name=consumer,proto3,oneof"`
}

type StepData_MemoryStats struct {
	MemoryStats *MemoryStats `protobuf:"bytes,44,opt,name=memory_stats,json=memoryStats,proto3,oneof"`
}

func (*StepData_B) isStepData_Data() {}

func (*StepData_I) isStepData_Data() {}

func (*StepData_F) isStepData_Data() {}

func (*StepData_S) isStepData_Data() {}

func (*StepData_M) isStepData_Data() {}

func (*StepData_Error) isStepData_Data() {}

func (*StepData_Credential) isStepData_Data() {}

func (*StepData_Route) isStepData_Data() {}

func (*StepData_Service) isStepData_Data() {}

func (*StepData_Consumer) isStepData_Data() {}

func (*StepData_MemoryStats) isStepData_Data() {}

type RpcCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequence int64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are assignable to Call:
	//	*RpcCall_CmdGetPluginNames
	//	*RpcCall_CmdGetPluginInfo
	//	*RpcCall_CmdStartInstance
	//	*RpcCall_CmdGetInstanceStatus
	//	*RpcCall_CmdCloseInstance
	//	*RpcCall_CmdHandleEvent
	//	*RpcCall_CmdStep
	Call isRpcCall_Call `protobuf_oneof:"call"`
}

func (x *RpcCall) Reset() {
	*x = RpcCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCall) ProtoMessage() {}

func (x *RpcCall) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCall.ProtoReflect.Descriptor instead.
func (*RpcCall) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{15}
}

func (x *RpcCall) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (m *RpcCall) GetCall() isRpcCall_Call {
	if m != nil {
		return m.Call
	}
	return nil
}

func (x *RpcCall) GetCmdGetPluginNames() *CmdGetPluginNames {
	if x, ok := x.GetCall().(*RpcCall_CmdGetPluginNames); ok {
		return x.CmdGetPluginNames
	}
	return nil
}

func (x *RpcCall) GetCmdGetPluginInfo() *CmdGetPluginInfo {
	if x, ok := x.GetCall().(*RpcCall_CmdGetPluginInfo); ok {
		return x.CmdGetPluginInfo
	}
	return nil
}

func (x *RpcCall) GetCmdStartInstance() *CmdStartInstance {
	if x, ok := x.GetCall().(*RpcCall_CmdStartInstance); ok {
		return x.CmdStartInstance
	}
	return nil
}

func (x *RpcCall) GetCmdGetInstanceStatus() *CmdGetInstanceStatus {
	if x, ok := x.GetCall().(*RpcCall_CmdGetInstanceStatus); ok {
		return x.CmdGetInstanceStatus
	}
	return nil
}

func (x *RpcCall) GetCmdCloseInstance() *CmdCloseInstance {
	if x, ok := x.GetCall().(*RpcCall_CmdCloseInstance); ok {
		return x.CmdCloseInstance
	}
	return nil
}

func (x *RpcCall) GetCmdHandleEvent() *CmdHandleEvent {
	if x, ok := x.GetCall().(*RpcCall_CmdHandleEvent); ok {
		return x.CmdHandleEvent
	}
	return nil
}

func (x *RpcCall) GetCmdStep() *StepData {
	if x, ok := x.GetCall().(*RpcCall_CmdStep); ok {
		return x.CmdStep
	}
	return nil
}

type isRpcCall_Call interface {
	isRpcCall_Call()
}

type RpcCall_CmdGetPluginNames struct {
	CmdGetPluginNames *CmdGetPluginNames `protobuf:"bytes,31,opt,name=cmd_get_plugin_names,json=cmdGetPluginNames,proto3,oneof"`
}

type RpcCall_CmdGetPluginInfo struct {
	CmdGetPluginInfo *CmdGetPluginInfo `protobuf:"bytes,32,opt,name=cmd_get_plugin_info,json=cmdGetPluginInfo,proto3,oneof"`
}

type RpcCall_CmdStartInstance struct {
	CmdStartInstance *CmdStartInstance `protobuf:"bytes,33,opt,name=cmd_start_instance,json=cmdStartInstance,proto3,oneof"`
}

type RpcCall_CmdGetInstanceStatus struct {
	CmdGetInstanceStatus *CmdGetInstanceStatus `protobuf:"bytes,34,opt,name=cmd_get_instance_status,json=cmdGetInstanceStatus,proto3,oneof"`
}

type RpcCall_CmdCloseInstance struct {
	CmdCloseInstance *CmdCloseInstance `protobuf:"bytes,35,opt,name=cmd_close_instance,json=cmdCloseInstance,proto3,oneof"`
}

type RpcCall_CmdHandleEvent struct {
	CmdHandleEvent *CmdHandleEvent `protobuf:"bytes,36,opt,name=cmd_handle_event,json=cmdHandleEvent,proto3,oneof"`
}

type RpcCall_CmdStep struct {
	CmdStep *StepData `protobuf:"bytes,37,opt,name=cmd_step,json=cmdStep,proto3,oneof"`
}

func (*RpcCall_CmdGetPluginNames) isRpcCall_Call() {}

func (*RpcCall_CmdGetPluginInfo) isRpcCall_Call() {}

func (*RpcCall_CmdStartInstance) isRpcCall_Call() {}

func (*RpcCall_CmdGetInstanceStatus) isRpcCall_Call() {}

func (*RpcCall_CmdCloseInstance) isRpcCall_Call() {}

func (*RpcCall_CmdHandleEvent) isRpcCall_Call() {}

func (*RpcCall_CmdStep) isRpcCall_Call() {}

type PluginNames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *PluginNames) Reset() {
	*x = PluginNames{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginNames) ProtoMessage() {}

func (x *PluginNames) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginNames.ProtoReflect.Descriptor instead.
func (*PluginNames) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{16}
}

func (x *PluginNames) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type PluginInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UpdatedAt int64    `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LoadedAt  int64    `protobuf:"varint,3,opt,name=loaded_at,json=loadedAt,proto3" json:"loaded_at,omitempty"`
	Phases    []string `protobuf:"bytes,4,rep,name=phases,proto3" json:"phases,omitempty"`
	Version   string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Priority  int32    `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Schema    string   `protobuf:"bytes,7,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{17}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *PluginInfo) GetLoadedAt() int64 {
	if x != nil {
		return x.LoadedAt
	}
	return 0
}

func (x *PluginInfo) GetPhases() []string {
	if x != nil {
		return x.Phases
	}
	return nil
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PluginInfo) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type InstanceStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InstanceId int32  `protobuf:"varint,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Config     string `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	StartedAt  int64  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
}

func (x *InstanceStatus) Reset() {
	*x = InstanceStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceStatus) ProtoMessage() {}

func (x *InstanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceStatus.ProtoReflect.Descriptor instead.
func (*InstanceStatus) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{18}
}

func (x *InstanceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstanceStatus) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *InstanceStatus) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *InstanceStatus) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

type RpcReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequence int64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are assignable to Return:
	//	*RpcReturn_PluginNames
	//	*RpcReturn_PluginInfo
	//	*RpcReturn_InstanceStatus
	//	*RpcReturn_StepData
	Return isRpcReturn_Return `protobuf_oneof:"return"`
}

func (x *RpcReturn) Reset() {
	*x = RpcReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcReturn) ProtoMessage() {}

func (x *RpcReturn) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcReturn.ProtoReflect.Descriptor instead.
func (*RpcReturn) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{19}
}

func (x *RpcReturn) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (m *RpcReturn) GetReturn() isRpcReturn_Return {
	if m != nil {
		return m.Return
	}
	return nil
}

func (x *RpcReturn) GetPluginNames() *PluginNames {
	if x, ok := x.GetReturn().(*RpcReturn_PluginNames); ok {
		return x.PluginNames
	}
	return nil
}

func (x *RpcReturn) GetPluginInfo() *PluginInfo {
	if x, ok := x.GetReturn().(*RpcReturn_PluginInfo); ok {
		return x.PluginInfo
	}
	return nil
}

func (x *RpcReturn) GetInstanceStatus() *InstanceStatus {
	if x, ok := x.GetReturn().(*RpcReturn_InstanceStatus); ok {
		return x.InstanceStatus
	}
	return nil
}

func (x *RpcReturn) GetStepData() *StepData {
	if x, ok := x.GetReturn().(*RpcReturn_StepData); ok {
		return x.StepData
	}
	return nil
}

type isRpcReturn_Return interface {
	isRpcReturn_Return()
}

type RpcReturn_PluginNames struct {
	PluginNames *PluginNames `protobuf:"bytes,31,opt,name=plugin_names,json=pluginNames,proto3,oneof"`
}

type RpcReturn_PluginInfo struct {
	PluginInfo *PluginInfo `protobuf:"bytes,32,opt,name=plugin_info,json=pluginInfo,proto3,oneof"`
}

type RpcReturn_InstanceStatus struct {
	InstanceStatus *InstanceStatus `protobuf:"bytes,33,opt,name=instance_status,json=instanceStatus,proto3,oneof"`
}

type RpcReturn_StepData struct {
	StepData *StepData `protobuf:"bytes,34,opt,name=step_data,json=stepData,proto3,oneof"`
}

func (*RpcReturn_PluginNames) isRpcReturn_Return() {}

func (*RpcReturn_PluginInfo) isRpcReturn_Return() {}

func (*RpcReturn_InstanceStatus) isRpcReturn_Return() {}

func (*RpcReturn_StepData) isRpcReturn_Return() {}

type MemoryStats_LuaSharedDicts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kong        *MemoryStats_LuaSharedDicts_DictStats `protobuf:"bytes,1,opt,name=kong,proto3" json:"kong,omitempty"`
	KongDbCache *MemoryStats_LuaSharedDicts_DictStats `protobuf:"bytes,2,opt,name=kong_db_cache,json=kongDbCache,proto3" json:"kong_db_cache,omitempty"`
}

func (x *MemoryStats_LuaSharedDicts) Reset() {
	*x = MemoryStats_LuaSharedDicts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoryStats_LuaSharedDicts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStats_LuaSharedDicts) ProtoMessage() {}

func (x *MemoryStats_LuaSharedDicts) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStats_LuaSharedDicts.ProtoReflect.Descriptor instead.
func (*MemoryStats_LuaSharedDicts) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{6, 0}
}

func (x *MemoryStats_LuaSharedDicts) GetKong() *MemoryStats_LuaSharedDicts_DictStats {
	if x != nil {
		return x.Kong
	}
	return nil
}

func (x *MemoryStats_LuaSharedDicts) GetKongDbCache() *MemoryStats_LuaSharedDicts_DictStats {
	if x != nil {
		return x.KongDbCache
	}
	return nil
}

type MemoryStats_WorkerLuaVm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HttpAllocatedGc int64 `protobuf:"varint,1,opt,name=http_allocated_gc,json=httpAllocatedGc,proto3" json:"http_allocated_gc,omitempty"`
	Pid             int64 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *MemoryStats_WorkerLuaVm) Reset() {
	*x = MemoryStats_WorkerLuaVm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoryStats_WorkerLuaVm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStats_WorkerLuaVm) ProtoMessage() {}

func (x *MemoryStats_WorkerLuaVm) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStats_WorkerLuaVm.ProtoReflect.Descriptor instead.
func (*MemoryStats_WorkerLuaVm) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{6, 1}
}

func (x *MemoryStats_WorkerLuaVm) GetHttpAllocatedGc() int64 {
	if x != nil {
		return x.HttpAllocatedGc
	}
	return 0
}

func (x *MemoryStats_WorkerLuaVm) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type MemoryStats_LuaSharedDicts_DictStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllocatedSlabs int64 `protobuf:"varint,1,opt,name=allocated_slabs,json=allocatedSlabs,proto3" json:"allocated_slabs,omitempty"`
	Capacity       int64 `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
}

func (x *MemoryStats_LuaSharedDicts_DictStats) Reset() {
	*x = MemoryStats_LuaSharedDicts_DictStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginsocket_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoryStats_LuaSharedDicts_DictStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStats_LuaSharedDicts_DictStats) ProtoMessage() {}

func (x *MemoryStats_LuaSharedDicts_DictStats) ProtoReflect() protoreflect.Message {
	mi := &file_pluginsocket_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStats_LuaSharedDicts_DictStats.ProtoReflect.Descriptor instead.
func (*MemoryStats_LuaSharedDicts_DictStats) Descriptor() ([]byte, []int) {
	return file_pluginsocket_proto_rawDescGZIP(), []int{6, 0, 0}
}

func (x *MemoryStats_LuaSharedDicts_DictStats) GetAllocatedSlabs() int64 {
	if x != nil {
		return x.AllocatedSlabs
	}
	return 0
}

func (x *MemoryStats_LuaSharedDicts_DictStats) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

var File_pluginsocket_proto protoreflect.FileDescriptor

var file_pluginsocket_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x1c, 0x0a, 0x0a, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x0e, 0x43, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xb1, 0x04, 0x0a, 0x05, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x68,
	0x6f, 0x73, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x12, 0x3b, 0x0a, 0x1a, 0x68, 0x74, 0x74, 0x70, 0x73, 0x5f, 0x72, 0x65,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x17, 0x68, 0x74, 0x74, 0x70, 0x73, 0x52,
	0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x67, 0x65, 0x78, 0x5f, 0x70, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x67, 0x65, 0x78,
	0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x69,
	0x70, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x74,
	0x72, 0x69, 0x70, 0x50, 0x61, 0x74, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c,
	0x70, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x6e, 0x69, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6e, 0x69, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x10, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0c, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x11, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x12, 0x3a, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x12, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0xb7,
	0x03, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x27,
	0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x77, 0x72, 0x69, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x72, 0x65, 0x61, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x12, 0x53, 0x0a, 0x12, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x08, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x22, 0x4a, 0x0a, 0x17, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x22, 0xa2, 0x04,
	0x0a, 0x0b, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x5a, 0x0a,
	0x10, 0x6c, 0x75, 0x61, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x64, 0x69, 0x63, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x4c, 0x75, 0x61, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x44, 0x69, 0x63, 0x74, 0x73, 0x52, 0x0e, 0x6c, 0x75, 0x61, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x44, 0x69, 0x63, 0x74, 0x73, 0x12, 0x55, 0x0a, 0x0f, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x73, 0x5f, 0x6c, 0x75, 0x61, 0x5f, 0x76, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4c, 0x75, 0x61, 0x56,
	0x6d, 0x52, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x4c, 0x75, 0x61, 0x56, 0x6d, 0x73,
	0x1a, 0x92, 0x02, 0x0a, 0x0e, 0x4c, 0x75, 0x61, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x44, 0x69,
	0x63, 0x74, 0x73, 0x12, 0x4e, 0x0a, 0x04, 0x6b, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x3a, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x2e, 0x4c, 0x75, 0x61, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x44, 0x69,
	0x63, 0x74, 0x73, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x04, 0x6b,
	0x6f, 0x6e, 0x67, 0x12, 0x5e, 0x0a, 0x0d, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x64, 0x62, 0x5f, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x6b, 0x6f, 0x6e,
	0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x4c, 0x75,
	0x61, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x44, 0x69, 0x63, 0x74, 0x73, 0x2e, 0x44, 0x69, 0x63,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x0b, 0x6b, 0x6f, 0x6e, 0x67, 0x44, 0x62, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x1a, 0x50, 0x0a, 0x09, 0x44, 0x69, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x27, 0x0a, 0x0f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x6c,
	0x61, 0x62, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x61, 0x6c, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x65, 0x64, 0x53, 0x6c, 0x61, 0x62, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70,
	0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x70,
	0x61, 0x63, 0x69, 0x74, 0x79, 0x1a, 0x4b, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4c,
	0x75, 0x61, 0x56, 0x6d, 0x12, 0x2a, 0x0a, 0x11, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x61, 0x6c, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x67, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0f, 0x68, 0x74, 0x74, 0x70, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x47, 0x63,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x70,
	0x69, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x6d, 0x64, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x26, 0x0a, 0x10, 0x43, 0x6d, 0x64, 0x47, 0x65,
	0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x3e, 0x0a, 0x10, 0x43, 0x6d, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22,
	0x37, 0x0a, 0x14, 0x43, 0x6d, 0x64, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x10, 0x43, 0x6d, 0x64, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x22, 0x50, 0x0a,
	0x0e, 0x43, 0x6d, 0x64, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x6b, 0x0a, 0x03, 0x4d, 0x61, 0x70, 0x12, 0x2e, 0x0a, 0x01, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4d, 0x61, 0x70, 0x2e, 0x4d, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x01, 0x6d, 0x1a, 0x34, 0x0a, 0x06, 0x4d, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xf7, 0x03, 0x0a,
	0x08, 0x53, 0x74, 0x65, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x01, 0x62, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x00, 0x52, 0x01, 0x62, 0x12, 0x0e, 0x0a, 0x01, 0x69, 0x18, 0x20, 0x20, 0x01, 0x28, 0x03, 0x48,
	0x00, 0x52, 0x01, 0x69, 0x12, 0x0e, 0x0a, 0x01, 0x66, 0x18, 0x21, 0x20, 0x01, 0x28, 0x01, 0x48,
	0x00, 0x52, 0x01, 0x66, 0x12, 0x0e, 0x0a, 0x01, 0x73, 0x18, 0x22, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x01, 0x73, 0x12, 0x29, 0x0a, 0x01, 0x6d, 0x18, 0x23, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4d, 0x61, 0x70, 0x48, 0x00, 0x52, 0x01, 0x6d, 0x12,
	0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x24, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x4f, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6b, 0x6f,
	0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x33, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x18, 0x29, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x48, 0x00, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x39, 0x0a,
	0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x2a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x00, 0x52,
	0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x72, 0x18, 0x2b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6b, 0x6f, 0x6e,
	0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08, 0x63, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x2c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6b,
	0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x73, 0x48,
	0x00, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x73, 0x42, 0x06,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x86, 0x05, 0x0a, 0x07, 0x52, 0x70, 0x63, 0x43, 0x61,
	0x6c, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x5a,
	0x0a, 0x14, 0x63, 0x6d, 0x64, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6b,
	0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6d, 0x64, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x48, 0x00, 0x52, 0x11, 0x63, 0x6d, 0x64, 0x47, 0x65, 0x74, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x57, 0x0a, 0x13, 0x63, 0x6d,
	0x64, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x20, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43,
	0x6d, 0x64, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x48,
	0x00, 0x52, 0x10, 0x63, 0x6d, 0x64, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x56, 0x0a, 0x12, 0x63, 0x6d, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x21, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6d, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x48, 0x00, 0x52, 0x10, 0x63, 0x6d, 0x64, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x63, 0x0a, 0x17, 0x63,
	0x6d, 0x64, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x22, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6b,
	0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6d, 0x64, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x14, 0x63, 0x6d, 0x64, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x56, 0x0a, 0x12, 0x63, 0x6d, 0x64, 0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x23, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6b,
	0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6d, 0x64, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x48, 0x00, 0x52, 0x10, 0x63, 0x6d, 0x64, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x10, 0x63, 0x6d, 0x64, 0x5f,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x24, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6d, 0x64, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x63, 0x6d, 0x64, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x3b, 0x0a, 0x08, 0x63, 0x6d,
	0x64, 0x5f, 0x73, 0x74, 0x65, 0x70, 0x18, 0x25, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6b,
	0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x07,
	0x63, 0x6d, 0x64, 0x53, 0x74, 0x65, 0x70, 0x42, 0x06, 0x0a, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x22,
	0x23, 0x0a, 0x0b, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x22, 0xc2, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6c, 0x6f, 0x61, 0x64, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x68, 0x61, 0x73, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x68, 0x61, 0x73, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22, 0x7c, 0x0a, 0x0e, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xce, 0x02, 0x0a, 0x09, 0x52, 0x70, 0x63, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x46, 0x0a, 0x0c, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x43, 0x0a, 0x0b, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x20, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x48, 0x00, 0x52, 0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x4f,
	0x0a, 0x0f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x21, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52,
	0x0e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x3d, 0x0a, 0x09, 0x73, 0x74, 0x65, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x22, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x08, 0x73, 0x74, 0x65, 0x70, 0x44, 0x61, 0x74, 0x61, 0x42, 0x08,
	0x0a, 0x06, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x42, 0x18, 0x5a, 0x16, 0x2e, 0x2f, 0x6b, 0x6f,
	0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pluginsocket_proto_rawDescOnce sync.Once
	file_pluginsocket_proto_rawDescData = file_pluginsocket_proto_rawDesc
)

func file_pluginsocket_proto_rawDescGZIP() []byte {
	file_pluginsocket_proto_rawDescOnce.Do(func() {
		file_pluginsocket_proto_rawDescData = protoimpl.X.CompressGZIP(file_pluginsocket_proto_rawDescData)
	})
	return file_pluginsocket_proto_rawDescData
}

var file_pluginsocket_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_pluginsocket_proto_goTypes = []interface{}{
	(*ServiceKey)(nil),                           // 0: kong_plugin_protocol.ServiceKey
	(*CertificateKey)(nil),                       // 1: kong_plugin_protocol.CertificateKey
	(*Route)(nil),                                // 2: kong_plugin_protocol.Route
	(*Service)(nil),                              // 3: kong_plugin_protocol.Service
	(*Consumer)(nil),                             // 4: kong_plugin_protocol.Consumer
	(*AuthenticatedCredential)(nil),              // 5: kong_plugin_protocol.AuthenticatedCredential
	(*MemoryStats)(nil),                          // 6: kong_plugin_protocol.MemoryStats
	(*CmdGetPluginNames)(nil),                    // 7: kong_plugin_protocol.CmdGetPluginNames
	(*CmdGetPluginInfo)(nil),                     // 8: kong_plugin_protocol.CmdGetPluginInfo
	(*CmdStartInstance)(nil),                     // 9: kong_plugin_protocol.CmdStartInstance
	(*CmdGetInstanceStatus)(nil),                 // 10: kong_plugin_protocol.CmdGetInstanceStatus
	(*CmdCloseInstance)(nil),                     // 11: kong_plugin_protocol.CmdCloseInstance
	(*CmdHandleEvent)(nil),                       // 12: kong_plugin_protocol.CmdHandleEvent
	(*Map)(nil),                                  // 13: kong_plugin_protocol.Map
	(*StepData)(nil),                             // 14: kong_plugin_protocol.StepData
	(*RpcCall)(nil),                              // 15: kong_plugin_protocol.RpcCall
	(*PluginNames)(nil),                          // 16: kong_plugin_protocol.PluginNames
	(*PluginInfo)(nil),                           // 17: kong_plugin_protocol.PluginInfo
	(*InstanceStatus)(nil),                       // 18: kong_plugin_protocol.InstanceStatus
	(*RpcReturn)(nil),                            // 19: kong_plugin_protocol.RpcReturn
	(*MemoryStats_LuaSharedDicts)(nil),           // 20: kong_plugin_protocol.MemoryStats.LuaSharedDicts
	(*MemoryStats_WorkerLuaVm)(nil),              // 21: kong_plugin_protocol.MemoryStats.WorkerLuaVm
	(*MemoryStats_LuaSharedDicts_DictStats)(nil), // 22: kong_plugin_protocol.MemoryStats.LuaSharedDicts.DictStats
	nil, // 23: kong_plugin_protocol.Map.MEntry
}
var file_pluginsocket_proto_depIdxs = []int32{
	0,  // 0: kong_plugin_protocol.Route.service:type_name -> kong_plugin_protocol.ServiceKey
	1,  // 1: kong_plugin_protocol.Service.client_certificate:type_name -> kong_plugin_protocol.CertificateKey
	20, // 2: kong_plugin_protocol.MemoryStats.lua_shared_dicts:type_name -> kong_plugin_protocol.MemoryStats.LuaSharedDicts
	21, // 3: kong_plugin_protocol.MemoryStats.workers_lua_vms:type_name -> kong_plugin_protocol.MemoryStats.WorkerLuaVm
	23, // 4: kong_plugin_protocol.Map.m:type_name -> kong_plugin_protocol.Map.MEntry
	13, // 5: kong_plugin_protocol.StepData.m:type_name -> kong_plugin_protocol.Map
	5,  // 6: kong_plugin_protocol.StepData.credential:type_name -> kong_plugin_protocol.AuthenticatedCredential
	2,  // 7: kong_plugin_protocol.StepData.route:type_name -> kong_plugin_protocol.Route
	3,  // 8: kong_plugin_protocol.StepData.service:type_name -> kong_plugin_protocol.Service
	4,  // 9: kong_plugin_protocol.StepData.consumer:type_name -> kong_plugin_protocol.Consumer
	6,  // 10: kong_plugin_protocol.StepData.memory_stats:type_name -> kong_plugin_protocol.MemoryStats
	7,  // 11: kong_plugin_protocol.RpcCall.cmd_get_plugin_names:type_name -> kong_plugin_protocol.CmdGetPluginNames
	8,  // 12: kong_plugin_protocol.RpcCall.cmd_get_plugin_info:type_name -> kong_plugin_protocol.CmdGetPluginInfo
	9,  // 13: kong_plugin_protocol.RpcCall.cmd_start_instance:type_name -> kong_plugin_protocol.CmdStartInstance
	10, // 14: kong_plugin_protocol.RpcCall.cmd_get_instance_status:type_name -> kong_plugin_protocol.CmdGetInstanceStatus
	11, // 15: kong_plugin_protocol.RpcCall.cmd_close_instance:type_name -> kong_plugin_protocol.CmdCloseInstance
	12, // 16: kong_plugin_protocol.RpcCall.cmd_handle_event:type_name -> kong_plugin_protocol.CmdHandleEvent
	14, // 17: kong_plugin_protocol.RpcCall.cmd_step:type_name -> kong_plugin_protocol.StepData
	16, // 18: kong_plugin_protocol.RpcReturn.plugin_names:type_name -> kong_plugin_protocol.PluginNames
	17, // 19: kong_plugin_protocol.RpcReturn.plugin_info:type_name -> kong_plugin_protocol.PluginInfo
	18, // 20: kong_plugin_protocol.RpcReturn.instance_status:type_name -> kong_plugin_protocol.InstanceStatus
	14, // 21: kong_plugin_protocol.RpcReturn.step_data:type_name -> kong_plugin_protocol.StepData
	22, // 22: kong_plugin_protocol.MemoryStats.LuaSharedDicts.kong:type_name -> kong_plugin_protocol.MemoryStats.LuaSharedDicts.DictStats
	22, // 23: kong_plugin_protocol.MemoryStats.LuaSharedDicts.kong_db_cache:type_name -> kong_plugin_protocol.MemoryStats.LuaSharedDicts.DictStats
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_pluginsocket_proto_init() }
func file_pluginsocket_proto_init() {
	if File_pluginsocket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pluginsocket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CertificateKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Route); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Consumer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticatedCredential); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemoryStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetPluginNames); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetPluginInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdStartInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdGetInstanceStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdCloseInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdHandleEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Map); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StepData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginNames); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstanceStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemoryStats_LuaSharedDicts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemoryStats_WorkerLuaVm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginsocket_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemoryStats_LuaSharedDicts_DictStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pluginsocket_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*StepData_B)(nil),
		(*StepData_I)(nil),
		(*StepData_F)(nil),
		(*StepData_S)(nil),
		(*StepData_M)(nil),
		(*StepData_Error)(nil),
		(*StepData_Credential)(nil),
		(*StepData_Route)(nil),
		(*StepData_Service)(nil),
		(*StepData_Consumer)(nil),
		(*StepData_MemoryStats)(nil),
	}
	file_pluginsocket_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*RpcCall_CmdGetPluginNames)(nil),
		(*RpcCall_CmdGetPluginInfo)(nil),
		(*RpcCall_CmdStartInstance)(nil),
		(*RpcCall_CmdGetInstanceStatus)(nil),
		(*RpcCall_CmdCloseInstance)(nil),
		(*RpcCall_CmdHandleEvent)(nil),
		(*RpcCall_CmdStep)(nil),
	}
	file_pluginsocket_proto_msgTypes[19].OneofWrappers = []interface{}{
		(*RpcReturn_PluginNames)(nil),
		(*RpcReturn_PluginInfo)(nil),
		(*RpcReturn_InstanceStatus)(nil),
		(*RpcReturn_StepData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pluginsocket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluginsocket_proto_goTypes,
		DependencyIndexes: file_pluginsocket_proto_depIdxs,
		MessageInfos:      file_pluginsocket_proto_msgTypes,
	}.Build()
	File_pluginsocket_proto = out.File
	file_pluginsocket_proto_rawDesc = nil
	file_pluginsocket_proto_goTypes = nil
	file_pluginsocket_proto_depIdxs = nil
}
